function setupRenameSheetUI() {
  const ss=SpreadsheetApp.getActiveSpreadsheet(), sheet1=ss.getSheetByName(CONFIG.SHEET_NAME); if(!sheet1){SpreadsheetApp.getUi().alert("Loi: Khong tim thay "+CONFIG.SHEET_NAME);return;}
  let sheet2=ss.getSheetByName("Sheet2"); if(!sheet2) sheet2=ss.insertSheet("Sheet2");
  const lastRow=sheet1.getLastRow(); if(lastRow<2){ss.toast("Sheet1 chua co du lieu.","Setup Info",3);return;}
  const roots=new Set(sheet1.getRange(2,1,lastRow-1,1).getValues().flat().filter(Boolean).map(String).map(s=>s.trim()));
  if(roots.size) sheet2.getRange("A1").setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList([...roots].sort(),true).setAllowInvalid(false).build());
  sheet2.getRange("A2").clearDataValidations().clearContent(); sheet2.getRange("A1").clearContent();
}
function onEdit(e){if(!e||!e.range)return;const r=e.range,s=r.getSheet();if(s.getName()==="Sheet2"&&r.getRow()===1&&r.getColumn()===1){const root=r.getValue(),a2=s.getRange("A2");a2.clearContent().clearDataValidations();if(!root)return;const s1=e.source.getSheetByName(CONFIG.SHEET_NAME);if(!s1)return;const n=s1.getLastRow();if(n<2)return;const paths=new Set(s1.getRange(2,1,n-1,2).getValues().filter(x=>String(x[0]).trim()===String(root).trim()&&x[1]).map(x=>String(x[1]).trim()));if(paths.size)a2.setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList([...paths].sort(),true).setAllowInvalid(false).build());}}
function scanRenameableCodes(){const ss=SpreadsheetApp.getActiveSpreadsheet(),ui=SpreadsheetApp.getUi(),lock=LockService.getScriptLock();if(!lock.tryLock(10000)){ss.toast("He thong dang ban.","System Busy",5);return;}try{const sh=ss.getSheetByName("Sheet2");if(!sh){ui.alert("Loi: Khong tim thay tab 'Sheet2'.");return;}ss.setActiveSheet(sh);const root=sh.getRange("A1").getValue(),path=sh.getRange("A2").getValue();if(!root||!path){ui.alert("Loi: Thieu Root (A1) hoac Path (A2).");return;}const map=buildLookupMap_(ss.getSheetByName(CONFIG.SHEET_NAME),root,path),codes=[];Object.keys(map).forEach(code=>{const d=map[code];if(d.releasedLink&&d.link2D&&d.releasedRow!==d.link2DRow)codes.push([code,d.releasedName,d.link2DName,"Cho xac nhan"]);});const old=sh.getLastRow();if(old>=3)sh.getRange(3,1,old-2,4).clearContent().clearFormat();sh.getRange(3,1,1,4).setValues([["Code","Released","2D & pdf","Status"]]).setFontWeight("bold");if(codes.length){sh.getRange(4,1,codes.length,4).setValues(codes);sh.autoResizeColumns(1,4);}SpreadsheetApp.flush();}finally{lock.releaseLock();}}
function runBatchRenameSync(){const ss=SpreadsheetApp.getActiveSpreadsheet(),ui=SpreadsheetApp.getUi(),sh=ss.getSheetByName("Sheet2");if(!sh){ui.alert("Loi: Khong tim thay tab 'Sheet2'.");return;}const last=sh.getLastRow();if(last<4){ui.alert("Loi: Danh sach Code trong. Vui long quet ma truoc.");return;}const count=last-3;if(ui.alert('Xac nhan Dong bo',`He thong se doi ten thuc te cho ${count} file tren Drive.`,ui.ButtonSet.YES_NO)!==ui.Button.YES)return;const lock=LockService.getScriptLock();if(!lock.tryLock(30000)){ui.alert("He thong dang ban.");return;}try{const map=buildLookupMap_(ss.getSheetByName(CONFIG.SHEET_NAME),sh.getRange("A1").getValue(),sh.getRange("A2").getValue()),vals=sh.getRange(4,1,count,1).getValues();let ok=0;for(let i=0;i<count;i++){const code=String(vals[i][0]||'').trim().toUpperCase(),cell=sh.getRange(i+4,4),d=map[code];if(!d){cell.setValue("Loi - Khong tim thay Code");continue;}const idR=extractFileId_(d.releasedLink),id2=extractFileId_(d.link2D);if(!idR||!id2){cell.setValue("Loi - Thieu file lien ket");continue;}try{const rf=Drive.Files.get(idR,{supportsAllDrives:true,fields:"title"}),f2=Drive.Files.get(id2,{supportsAllDrives:true,fields:"title,parents"});const base=rf.title.replace(/\.[^.]+$/,''),ext=f2.title.includes('.')?f2.title.substring(f2.title.lastIndexOf('.')):'';const newName=base+ext;if(f2.title===newName){cell.setValue("Bo qua - Ten da chuan");continue;}let dup=false;if(f2.parents&&f2.parents.length){const q=`title = '${newName.replace(/'/g,"\\'")}' and '${f2.parents[0].id}' in parents and trashed = false`;const sr=Drive.Files.list({q,maxResults:10,supportsAllDrives:true,includeItemsFromAllDrives:true});dup=(sr.items||[]).some(x=>x.id!==id2);}if(dup){cell.setValue("Can kiem tra thu cong - Da co file trung ten");continue;}const updated=Drive.Files.patch({title:newName},id2,{supportsAllDrives:true,fields:"title"});if(updated&&updated.title===newName){cell.setValue("Da dong bo: "+newName);sh.getRange(i+4,3).setValue(newName);ok++;}else cell.setValue("Loi he thong - API khong luu duoc ten moi");}catch(err){cell.setValue("Loi API: "+err.message);}Utilities.sleep(300);}ss.toast(`Da doi ten thanh cong ${ok}/${count} file!`,"Sync Complete",8);}finally{lock.releaseLock();}}
function buildLookupMap_(sheet1,targetRoot,targetPath){const out={};if(!sheet1)return out;const n=sheet1.getLastRow();if(n<2)return out;const meta=sheet1.getRange(2,1,n-1,4).getValues(),form=sheet1.getRange(2,7,n-1,2).getFormulas(),vals=sheet1.getRange(2,7,n-1,2).getValues();for(let i=0;i<meta.length;i++){if(meta[i][0]==targetRoot&&meta[i][1]==targetPath&&meta[i][3]){const code=String(meta[i][3]).trim().toUpperCase();if(!out[code])out[code]={releasedLink:"",link2D:"",releasedRow:-1,link2DRow:-1,releasedName:"",link2DName:""};const g=form[i][0]||vals[i][0],h=form[i][1]||vals[i][1];if(g){out[code].releasedLink=g;out[code].releasedRow=i;out[code].releasedName=meta[i][2];}if(h){out[code].link2D=h;out[code].link2DRow=i;out[code].link2DName=meta[i][2];}}}return out;}
function extractFileId_(text){if(!text)return null;const m=String(text).match(/[-\w]{25,}/);return m?m[0]:null;}