function runFullScan() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CONFIG.SHEET_NAME);
  ss.setActiveSheet(sheet);
  if (sheet.getFilter()) sheet.getFilter().remove();
  ss.toast("Dang quet bang Hybrid Engine...", "Drive Scanner", -1);
  try { const check = Drive.Files; } catch (e) { SpreadsheetApp.getUi().alert("Loi: Chua bat 'Drive API' trong Services."); return; }
  const ROUTING = {};
  for (const parentId in CONFIG.DRAWING.folders) { const targetCol = CONFIG.DRAWING.folders[parentId]; const targets = {}; CONFIG.DRAWING.subFolders.forEach(sub => targets[sub] = targetCol); ROUTING[parentId] = { type: CONFIG.DRAWING.type, pathName: "", targets: targets }; }
  for (const parentId in CONFIG.ACCESSORY.folders) { let rawTargets = CONFIG.ACCESSORY.folders[parentId].targets; if (rawTargets === 'DEFAULT') rawTargets = CONFIG.ACCESSORY.DEFAULT_TARGETS; ROUTING[parentId] = { type: CONFIG.ACCESSORY.type, pathName: CONFIG.ACCESSORY.folders[parentId].pathName, targets: rawTargets }; }
  const fileKeyToDataMap = {}; let filesFound = 0;
  for (const parentId in ROUTING) { try { const fileType = ROUTING[parentId].type; const pathName = ROUTING[parentId].pathName || ""; const rawRules = ROUTING[parentId].targets; const normalizedRules = {}; for (let key in rawRules) normalizedRules[key.trim().toLowerCase()] = rawRules[key]; const parentFolder = DriveApp.getFolderById(parentId); const subFolders = parentFolder.getFolders(); while (subFolders.hasNext()) { const subFolder = subFolders.next(); const cleanSubName = subFolder.getName().trim().toLowerCase(); if (normalizedRules[cleanSubName]) filesFound += scanFilesInFolderApi_(subFolder.getId(), normalizedRules[cleanSubName], fileType, (fileType === '11.1_Drawing' ? subFolder.getName() : pathName), fileKeyToDataMap); } } catch (e) { Logger.log(`Loi: ${e.message}`); } }
  const outputArray = []; for (const key in fileKeyToDataMap) { const item = fileKeyToDataMap[key]; outputArray.push([item.fileType, item.folderPath, item.baseFileName, item.code, item.version, item.releaseDay, item.linkReleased, item.link2D, item.link3D]); }
  outputArray.sort((a, b) => { const cmpA = a[0].localeCompare(b[0]); if (cmpA !== 0) return cmpA; const cmpB = a[1].localeCompare(b[1]); if (cmpB !== 0) return cmpB; return a[2].localeCompare(b[2]); });
  if (outputArray.length > 0) { const maxRow = sheet.getLastRow(); if (maxRow > 1) sheet.getRange(2, 1, maxRow, 9).clearContent(); const requiredRows = 1 + outputArray.length; let currentMaxRows = sheet.getMaxRows(); if (requiredRows > currentMaxRows) { sheet.insertRowsAfter(currentMaxRows, requiredRows - currentMaxRows); currentMaxRows = requiredRows; } sheet.getRange(2, 4, outputArray.length, 1).setNumberFormat('@'); sheet.getRange(2, 6, outputArray.length, 1).setNumberFormat('@'); sheet.getRange(2, 1, outputArray.length, 9).setValues(outputArray).setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP); if (currentMaxRows > requiredRows) sheet.deleteRows(requiredRows + 1, currentMaxRows - requiredRows); const updateTime = Utilities.formatDate(new Date(), "GMT+7", "dd/MM/yyyy HH:mm:ss"); sheet.getRange("A1").setNote(`Tong hop: ${outputArray.length} ban ve\n(Tu ${filesFound} files goc)\nCap nhat luc: ${updateTime}`); writeLogExternal_(`[BACKEND] Quet xong. File: ${filesFound}. Dong: ${outputArray.length}`); ss.toast(`Da gop thanh ${outputArray.length} dong.`, "Scan Complete", 5); } else { writeLogExternal_(`[BACKEND] Khong tim thay file nao.`); ss.toast("Khong co du lieu", "Scan Complete", 3); }
}
function writeLogExternal_(message) { try { const logSS = SpreadsheetApp.openById(CONFIG.LOG_ID); const logSheet = logSS.getSheets()[0]; const now = Utilities.formatDate(new Date(), "GMT+7", "dd/MM/yyyy HH:mm:ss"); logSheet.insertRowBefore(2); logSheet.getRange(2, 1, 1, 2).setValues([[now, message]]); if (logSheet.getLastRow() > 2000) logSheet.deleteRows(2001, logSheet.getLastRow() - 2000); } catch (e) { console.error("Loi ghi log: " + e.message); } }
function scanFilesInFolderApi_(folderId, targetColumn, fileType, folderPathValue, fileKeyToDataMap) { let count = 0; let pageToken = null; do { try { const response = Drive.Files.list({ q: `'${folderId}' in parents and trashed = false`, maxResults: 1000, pageToken: pageToken, supportsAllDrives: true, includeItemsFromAllDrives: true, corpora: 'allDrives' }); const files = response.items || []; for (let i = 0; i < files.length; i++) { const file = files[i]; if (file.mimeType === 'application/vnd.google-apps.folder') continue; if (!CONFIG.ALLOWED_EXTENSIONS.some(ext => file.title.toLowerCase().endsWith(ext)) && file.mimeType !== 'application/vnd.google-apps.spreadsheet') continue; count++; const baseFileName = file.title.lastIndexOf('.') !== -1 ? file.title.substring(0, file.title.lastIndexOf('.')) : file.title; const key = baseFileName.toUpperCase(); const parts = baseFileName.split("_"); let code = parts[0] || "", version = "", revision = "", releaseDay = ""; parts.forEach(p => { if (/^V\d+/i.test(p)) version = p; if (/^R\d+/i.test(p)) revision = p; if (/^\d{1,2}[A-Za-z]{3}\d{4}$/i.test(p)) releaseDay = p; }); if (code.toUpperCase() === "PM") { const match = baseFileName.match(/PM_(.*?)(?=_)/i); if (match) code = "PM_" + match[1]; } const hyperlink = `=HYPERLINK("${file.alternateLink || file.webViewLink}", "${code}")`; if (!fileKeyToDataMap[key]) fileKeyToDataMap[key] = { fileType: fileType, folderPath: folderPathValue, baseFileName: baseFileName, code: code, version: version || revision || "R1", releaseDay: releaseDay, linkReleased: "", link2D: "", link3D: "" }; if (targetColumn === 'Released') fileKeyToDataMap[key].linkReleased = hyperlink; else if (targetColumn === '2D & pdf') fileKeyToDataMap[key].link2D = hyperlink; else if (targetColumn === '3D & Corel') fileKeyToDataMap[key].link3D = hyperlink; } pageToken = response.nextPageToken; } catch (e) { pageToken = null; } } while (pageToken); return count; }
function createDailyBackendTrigger() { const triggers = ScriptApp.getProjectTriggers(); for (const trigger of triggers) if (trigger.getHandlerFunction() === 'runFullScan') ScriptApp.deleteTrigger(trigger); ScriptApp.newTrigger('runFullScan').timeBased().atHour(6).nearMinute(00).everyDays(1).create(); ScriptApp.newTrigger('runFullScan').timeBased().atHour(12).nearMinute(00).everyDays(1).create(); SpreadsheetApp.getActiveSpreadsheet().toast("Da dat lich.", "Trigger Scheduled", 5); }