const LOG_FILE_ID = CONFIG.SYSTEM.LOG_FILE_ID;
const MAX_LOG_ROWS = CONFIG.SYSTEM.MAX_LOG_ROWS;
function logAction(actionType, details) { try { const now=Utilities.formatDate(new Date(),"Asia/Bangkok","yyyy-MM-dd HH:mm:ss"); const userEmail=Session.getActiveUser().getEmail()||"System/Trigger"; Sheets.Spreadsheets.Values.append({values:[[now,userEmail,actionType,details]]},LOG_FILE_ID,"Sheet1!A:D",{valueInputOption:"USER_ENTERED"}); } catch(e){ console.warn("Logging API failed: "+e.message); } }
function activateHomePage(){const ss=SpreadsheetApp.getActiveSpreadsheet(),sheet=ss.getSheetByName(CONFIG.SHEETS.HOMEPAGE);if(sheet)sheet.activate();else SpreadsheetApp.getUi().alert('Sheet "'+CONFIG.SHEETS.HOMEPAGE+'" khong ton tai.');}
function activateBomSearch(){jumpToSheet(CONFIG.SHEETS.SEARCH_RESULT)}
function activateRmSearch(){jumpToSheet(CONFIG.SHEETS.SEARCH_RM||"Search RM")}
function activateCostSearch(){jumpToSheet(CONFIG.SHEETS.COST_SEARCH)}
function activateBomCompare(){jumpToSheet(CONFIG.SHEETS.COMPARISON)}
function jumpToSheet(name){if(!name){SpreadsheetApp.getUi().alert("Sheet name is undefined in Config.");return;}const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name);s?SpreadsheetApp.setActiveSheet(s):SpreadsheetApp.getUi().alert('Sheet "'+name+'" khong ton tai.');}
function runSelectedExport(options){const start=new Date(),ss=SpreadsheetApp.getActiveSpreadsheet(),sheet=ss.getSheetByName(CONFIG.SHEETS.SEARCH_RESULT);if(!sheet)throw new Error('Sheet "'+CONFIG.SHEETS.SEARCH_RESULT+'" not found.');const dateStr=Utilities.formatDate(new Date(),ss.getSpreadsheetTimeZone(),"ddMMyy"),H15=sheet.getRange("H15").getDisplayValue().trim(),I15=sheet.getRange("I15").getDisplayValue().trim();if(!H15||!I15)throw new Error("Required cells (H15 or I15) are missing.");const formulas=sheet.getRange("A1:Z100").getFormulas();for(const row of formulas)for(const formula of row)if(formula.includes("#REF!"))throw new Error("Found #REF! error. Please fix it before exporting.");const fileBaseName=`${H15}_${I15}_${dateStr}_BOM`,result={};if(options.exportPDF||options.exportSheet){let tempCopy=ss.getSheetByName("SYS_TMP_EXPORT");if(!tempCopy)tempCopy=sheet.copyTo(ss).setName("SYS_TMP_EXPORT");else{tempCopy.showSheet();tempCopy.clear();sheet.getDataRange().copyTo(tempCopy.getRange(1,1));}tempCopy.showRows(1,tempCopy.getMaxRows());tempCopy.showColumns(1,tempCopy.getMaxColumns());tempCopy.getDataRange().copyTo(tempCopy.getRange(1,1),{contentsOnly:true});const checkValues=tempCopy.getRange("C15:H119").getValues();const hideFlags=checkValues.map(row=>[row[5]!==""&&!((row[0]!=="")||(row[1]!=="")||(row[2]!==""))]);batchHideRows(tempCopy,15,hideFlags);if(options.exportPDF){if(tempCopy.getLastColumn()>=19)tempCopy.hideColumn(tempCopy.getRange("S1"));const pdfUrl=`https://docs.google.com/spreadsheets/d/${ss.getId()}/export?format=pdf&gid=${tempCopy.getSheetId()}&range=A1:Z100&portrait=true&fitw=true&sheetnames=false&printtitle=false&pagenumbers=false&gridlines=false&fzr=false`,response=UrlFetchApp.fetch(pdfUrl,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(response.getResponseCode()!==200)throw new Error('API error '+response.getResponseCode()+': '+response.getContentText());result.pdfUrl=DriveApp.createFile(response.getBlob().setName(fileBaseName+".pdf")).getUrl();}if(options.exportSheet){const newFile=SpreadsheetApp.create(fileBaseName);tempCopy.copyTo(newFile).setName(fileBaseName);newFile.deleteSheet(newFile.getSheets()[0]);result.sheetUrl=newFile.getUrl();}tempCopy.hideSheet();}result.elapsed=`${((new Date()-start)/60000).toFixed(2)} mins`;logAction("EXPORT",`Export ${getExportTypeString(options)} (${fileBaseName}) - Success`);SpreadsheetApp.flush();return result;}
function getExportTypeString(options){const types=[];if(options.exportPDF)types.push("PDF");if(options.exportSheet)types.push("Sheet");return types.join(" + ");}
function batchHideRows(sheet,startRowIndex,values){if(!values||!values.length)return;const rows=[];for(let i=0;i<values.length;i++)if(!values[i][0])rows.push(startRowIndex+i);if(!rows.length)return;const requests=[];rows.sort((a,b)=>a-b);let start=rows[0],count=1;const add=(st,ct)=>requests.push({updateDimensionProperties:{range:{sheetId:sheet.getSheetId(),dimension:"ROWS",startIndex:st-1,endIndex:st-1+ct},properties:{hiddenByUser:true},fields:"hiddenByUser"}});for(let i=1;i<rows.length;i++){if(rows[i]===rows[i-1]+1)count++;else{add(start,count);start=rows[i];count=1;}}add(start,count);try{Sheets.Spreadsheets.batchUpdate({requests},sheet.getParent().getId());}catch(e){start=rows[0];count=1;for(let i=1;i<rows.length;i++){if(rows[i]===rows[i-1]+1)count++;else{sheet.hideRows(start,count);start=rows[i];count=1;}}sheet.hideRows(start,count);}}
function exportBomCostSheet(){const start=new Date(),ss=SpreadsheetApp.getActiveSpreadsheet(),mainSheet=ss.getSheetByName(CONFIG.SHEETS.COST_SEARCH);if(!mainSheet)throw new Error('Sheet "'+CONFIG.SHEETS.COST_SEARCH+'" not found.');const B2=mainSheet.getRange("B2").getDisplayValue().trim(),C2=mainSheet.getRange("C2").getDisplayValue().trim(),dateStr=Utilities.formatDate(new Date(),ss.getSpreadsheetTimeZone(),"ddMMyy");if(!B2||!C2)throw new Error('Missing B2 or C2 in '+CONFIG.SHEETS.COST_SEARCH);const exportName=`${B2}_${C2}_${dateStr}_BOM_COST`,newFile=SpreadsheetApp.create(exportName),defaultSheet=newFile.getSheets()[0],names=[CONFIG.SHEETS.COST_SEARCH,CONFIG.SHEETS.SYS_MAT,CONFIG.SHEETS.SYS_BOM,CONFIG.SHEETS.SYS_COST];let copied=0;for(const name of names){const src=ss.getSheetByName(name);if(src){src.copyTo(newFile).setName(name);copied++;}}if(copied)newFile.deleteSheet(defaultSheet);const copiedMain=newFile.getSheetByName(CONFIG.SHEETS.COST_SEARCH);if(copiedMain){refreshFormulas(copiedMain);copiedMain.getRange("B2").clearDataValidations();}logAction("EXPORT",`Export BOM Cost (${exportName}) - Success`);return{fileUrl:newFile.getUrl(),elapsed:`${((new Date()-start)/60000).toFixed(2)} mins`,exportType:"bomcost"};}
function getColLetter_(i){let t,l='';while(i>0){t=(i-1)%26;l=String.fromCharCode(t+65)+l;i=(i-t-1)/26;}return l;}
function refreshFormulas(sheet){const range=sheet.getDataRange(),formulas=range.getFormulas(),batchData=[],sheetName=sheet.getName();for(let r=0;r<formulas.length;r++){let c=0;while(c<formulas[r].length){if(formulas[r][c]){let start=c,row=[];while(c<formulas[r].length&&formulas[r][c])row.push(formulas[r][c++]);const s=getColLetter_(start+1),e=getColLetter_(start+row.length),a=row.length>1?`${s}${r+1}:${e}${r+1}`:`${s}${r+1}`;batchData.push({range:`${sheetName}!${a}`,values:[row]});}else c++;}}if(batchData.length)try{Sheets.Spreadsheets.Values.batchUpdate({valueInputOption:"USER_ENTERED",data:batchData},sheet.getParent().getId());}catch(e){for(let r=0;r<formulas.length;r++)for(let c=0;c<formulas[r].length;c++)if(formulas[r][c])sheet.getRange(r+1,c+1).setFormula(formulas[r][c]);}}